config/routes.rb
Rails.application.routes.draw do
  root                  'static_pages#home'
  resources :users

  get                     'sessions/new'
  get                     'order/pivot'
  get    'help',      to: 'static_pages#help'
  get    'about',     to: 'static_pages#about'
  get    'contact',   to: 'static_pages#contact'
  get    'sign_up',   to: 'users#new'
  get    'login',     to: 'sessions#new'
  post   'login',     to: 'sessions#create'
  delete 'login',     to: 'sessions#destroy'
  delete 'logout',    to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<% content_for(:html_title) { 'About' } %>

<h1>About</h1>

<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% content_for(:html_title) { 'Contact' } %>

<h1>Contact</h1>

<p>Find Contact here</p>

app/views/static_pages/help.html.erb
<% content_for(:html_title) { 'Help' } %>

<h1>Help</h1>

<p>Find help here</p>

app/views/static_pages/home.html.erb
<div class="h-800 p-5 bg-light border rounded-3">
  
  <h1>Welcome to the Sample App</h1>

  <h2>This is a home page for 
    <a href="https://railstutorial.com">Rails Tutorial</a>
  </h2>
  <div  class="mt-4 mb-4">
    <%= link_to("Sign up now!", sign_up_path, class: "btn btn-outline-secondary") unless session[:email].present? %>
  </div>
  <div class="row">
     <%= image_tag 'photo_2022-03-26_19-02-53.jpg',
                    size: "640x468",
                    class: "img-thumbnail" %>
  </div>
</div>