config/routes.rb
Rails.application.routes.draw do
  root                  'static_pages#home'
  resources :users

  get                     'sessions/new'
  get                     'order/pivot'
  get    'help',      to: 'static_pages#help'
  get    'about',     to: 'static_pages#about'
  get    'contact',   to: 'static_pages#contact'
  get    'sign_up',   to: 'users#new'
  get    'login',     to: 'sessions#new'
  post   'login',     to: 'sessions#create'
  delete 'login',     to: 'sessions#destroy'
  delete 'logout',    to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if obj.errors.any?  %>
  <div class="info">
    <div class="alert alert-danger">
      <span>The form contain: <%= pluralize(obj.errors.count, "error") %>.</span>
      <ul>
        <% obj.errors.each do |error| %>
         <li><%=  error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<%  end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert">
      <%= value %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container py-4">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-left">
      <%= link_to "About", about_path, class: "navbar-brand" %> 
      <%= link_to "Help", help_path, class: "navbar-brand" %>
      <%= link_to "Contact", contact_path, class: "navbar-brand" %>
    </div>
  </nav>
</div>
  <small>
    The <a href="https://railstutorial.org">Rails Tutorial</a>
  </small>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Sample App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <nav>
      <ul class="navbar-nav navbar-right">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Help", help_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to("Login", login_path, class: "nav-link") unless logged_in? %>
        </li>

        <% if logged_in? %>
        <li class="nav-item">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Actions
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li>
                    <%= link_to("Profile", current_user, class: "dropdown-item") unless controller_name == "users"%>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#">
                          <%= button_to 'Log out', login_path, method: :delete %>
                    </a>
                  </li>
                </ul>
              </li>
          </li>
        <% end %>
        </ul>
      </nav>
    </div>
  </div>
</nav>